#!/bin/bash -eux

CXX=clang++
CXXFLAGS='-g -O2 -fPIC'
LDFLAGS='-Wl,-rpath,$ORIGIN'
LDFLAGS_DSO="$LDFLAGS -shared"
LDFLAGS_BIN="$LDFLAGS -fPIE"

DART_SDK="/opt/dart-sdk"
OHOS_SDK="$HOME/tmp/command-line-tools/sdk/HarmonyOS-NEXT-DB2/openharmony"

build-main-dso() {
    $CXX $CXXFLAGS -c ../lib/{impl,taihe_rt,c_api}.cc
    $CXX $LDFLAGS_DSO -o impl.so {impl,taihe_rt,c_api}.o
}

build-node-dso() {
    $CXX $CXXFLAGS -c ../lib/node_api.cc
    $CXX $LDFLAGS_DSO -o node_api.node impl.so node_api.o
}

build-dart-dso() {
    $CXX $CXXFLAGS -c ../lib/dart_api.cc -I "$DART_SDK/include/"
    $CXX $LDFLAGS_DSO -o dart_api.so impl.so dart_api.o
}

build-dso() {
    build-main-dso
    build-node-dso
    build-dart-dso
    rm *.o
}

build-native-benchmark() {
    $CXX $CXXFLAGS $LDFLAGS_BIN -o app-native ../app-native/*.cc impl.so
}

build-dart-benchmark() {
    src_dir=../app-native/dart-to-c
    src_file=bin/dart_to_c.dart
    bin_file=bin/dart_to_c.exe
    (cd $src_dir && "$DART_SDK/bin/dart" compile exe $src_file)
    mv $src_dir/$bin_file dart-to-c
}

cd $(realpath $(dirname $0))
mkdir -p bin && cd bin

CXX="$OHOS_SDK/native/llvm/bin/aarch64-unknown-linux-ohos-clang++"

build-dso
build-native-benchmark
build-dart-benchmark
