#!/usr/bin/bash
cd `dirname $0`
cd ../compiler/tests/
coverage run -m -p pytest || exit 1
coverage run -p ../run-test ../../test/integer -c || exit 1
coverage run -p ../run-test ../../test/string -c || exit 1
coverage run -p ../run-test ../../test/rgb -c || exit 1
coverage combine
coverage report
