#!/usr/bin/env python3
import pytest

from antlr4 import FileStream
from taihe.parse.ast_generation import generate_ast
from taihe.semantic_analysis import Package, semantic_check, symbol_substitute

import os
from pathlib import Path
from taihe.exceptions import (
    EnumValueCollisionError,
    PackageAliasConflictError,
    PackageNameConflictError,
    PackageNotExistError,
    PackageNotImportedError,
    QualifierError,
    RecursiveInclusionError,
    SymbolConflictError,
    SymbolConflictWithNamespaceError,
    SymbolNotExistError,
    SymbolNotImportedError,
)
from exceptiongroup import ExceptionGroup


def semantic_analysis(idl_dir):

    # Find all .taihe files in the containing directories
    src_paths = []
    for src_path in os.listdir(idl_dir):
        if os.path.splitext(src_path)[1].lower() == ".taihe":
            src_path = os.path.abspath(os.path.join(idl_dir, src_path))
            src_paths.append(src_path)

    # Parse into ASTs
    packages: list[Package] = []
    for src_path in src_paths:
        pktupl = tuple(os.path.splitext(os.path.basename(src_path))[0].split("."))
        try:
            spec = generate_ast(FileStream(src_path))
        except SyntaxError:
            raise SyntaxError(src_path) from None
        packages.append(Package(src_path, pktupl, spec))

    # Semantic analysis
    errors = []
    symbol_tables = symbol_substitute(errors, packages)
    semantic_check(errors, packages, symbol_tables)
    # print(type(errors[0]))
    return errors


def check_exception(test_cases):
    idl_dir = "test_cases/idl"
    for test_case in test_cases:
        for file in test_case[1]:
            with open(f"{idl_dir}/{file[0]}", "w") as f:
                f.writelines(file[1])
        errors = semantic_analysis(idl_dir)
        assert type(errors[0]) == test_case[0] 
        os.system("rm -rf test_cases/idl")
        os.system("mkdir test_cases/idl")


test_cases = [
    [PackageNotExistError, [['package.taihe', ['use a; \n']]]],

    [PackageAliasConflictError, 
    [['package.taihe', ['use package.example1 as example; \n', 
                        'use package.example2 as example; \n']],
    ['package.example1.taihe', ['\n']],
    ['package.example2.taihe', ['\n']]]],
    
    [PackageNotExistError, 
    [['package.taihe', ['from package.example2 use A; \n']],
    ['package.example1.taihe', ['struct A { \n', '    a: i32; \n', '} \n']]]]

]

if __name__ == "__main__":
    check_exception(test_cases)