#!/usr/bin/env python3
import pytest

from antlr4 import FileStream
from taihe.parse.ast_generation import generate_ast
from taihe.semantic_analysis import Package, semantic_check, symbol_substitute

import os
from pathlib import Path
from taihe.exceptions import (
    EnumValueCollisionError,
    PackageAliasConflictError,
    PackageNameConflictError,
    PackageNotExistError,
    PackageNotImportedError,
    QualifierError,
    RecursiveInclusionError,
    SymbolConflictError,
    SymbolConflictWithNamespaceError,
    SymbolNotExistError,
    SymbolNotImportedError,
)


def semantic_analysis(idl_dir):

    # Find all .taihe files in the containing directories
    src_paths = []
    for src_path in os.listdir(idl_dir):
        if os.path.splitext(src_path)[1].lower() == ".taihe":
            src_path = os.path.abspath(os.path.join(idl_dir, src_path))
            src_paths.append(src_path)

    # Parse into ASTs
    packages: list[Package] = []
    for src_path in src_paths:
        pktupl = tuple(os.path.splitext(os.path.basename(src_path))[0].split("."))
        try:
            spec = generate_ast(FileStream(src_path))
        except SyntaxError:
            raise SyntaxError(src_path) from None
        packages.append(Package(src_path, pktupl, spec))

    # Semantic analysis
    errors = []
    symbol_tables = symbol_substitute(errors, packages)
    semantic_check(errors, packages, symbol_tables)
    # print(type(errors[0]))
    return errors


def check_exception(test_cases):
    idl_dir = "test_cases/idl"
    for test_case in test_cases:
        for file in test_case[1]:
            with open(f"{idl_dir}/{file[0]}", "w") as f:
                f.writelines(file[1])
        errors = semantic_analysis(idl_dir)
        assert type(errors[0]) == test_case[0] 
        os.system("rm -rf test_cases/idl")
        os.system("mkdir test_cases/idl")


test_cases = [
    [PackageNotExistError, [['package.taihe', ['use a; \n']]]],

    [PackageAliasConflictError, 
    [['package.taihe', ['use package.example1 as example; \n', 
                        'use package.example2 as example; \n']],
    ['package.example1.taihe', ['\n']],
    ['package.example2.taihe', ['\n']]]],
    
    [PackageNotExistError, 
    [['package.taihe', ['from package.example2 use A; \n']],
    ['package.example1.taihe', ['struct A { \n', '    a: i32; \n', '} \n']]]],

    [SymbolConflictWithNamespaceError, 
    [['package.taihe', ['use package.example1.a; \n',
                        'from package.example1 use a;']],
    ['package.example1.taihe', ['struct a { \n', '    A: i32; \n', '} \n']],
    ['package.example1.a.taihe', []]]],

    [QualifierError, [['package.taihe', ['function bad_func(a: mut i32): (); \n']]]],

    [QualifierError, [['package.taihe', ['enum Enum { \n',
                                              '    A; \n',
                                              '} \n',
                                        'struct Struct { \n',
                                              '    a: Enum; \n',
                                              '} \n',
                                        'function bad_func(a: mut Struct, b: mut Enum): (); \n']]]],

    [SymbolConflictError, [['package.taihe', ['function bad_func(a: i32, a: i32): (); \n']]]],

    [SymbolConflictError, [['package.taihe', ['enum BadEnum { \n',
                                              '    A; \n',
                                              '    A; \n',
                                              '} \n']]]],

    [EnumValueCollisionError, [['package.taihe', ['enum BadEnum { \n',
                                              '    A; \n',
                                              '    B=1-2; \n',
                                              '    C; \n',
                                              '} \n']]]],

    [EnumValueCollisionError, [['package.taihe', ['enum BadEnum { \n',
                                              '    A=43; \n',
                                              '    B=if (7 << 1 + 1) + (3 * 3 - 2 & 11) == 31 && 1 + 1 == 2 then 42 else 10; \n',
                                              '    C=43; \n',
                                              '} \n']]]],

    [SymbolNotExistError, 
    [['package.taihe', ['from package.example1 use A; \n']],
    ['package.example1.taihe', []]]],

    [SymbolConflictError, 
    [['package.taihe', ['from package.example1 use A as a; \n', 
                        'from package.example2 use A as a; \n']],
    ['package.example1.taihe', ['struct A { \n', '    a: i32; \n', '} \n']],
    ['package.example2.taihe', ['struct A { \n', '    a: i32; \n', '} \n']]]],

    [SymbolNotImportedError, [['package.taihe', ['struct BadStruct { \n',
                                              '    a: UnimportedType; \n',
                                              '} \n']]]],

    [PackageNotImportedError, [['package.taihe', ['struct BadStruct { \n',
                                              '    a: unimported.package.Type; \n',
                                              '} \n']]]],

    [SymbolNotExistError, [['package.taihe', ['use package.example1; \n',
                                              'struct BadStruct { \n',
                                              '    a: package.example1.B; \n',
                                              '} \n']],
                            ['package.example1.taihe', ['struct A { \n', '    a: i32; \n', '} \n']]]],

    [SymbolConflictError, [['package.taihe', ['struct BadStruct { \n',
                                              '    a: i32; \n',
                                              '    a: i32; \n',
                                              '} \n']]]],

    [RecursiveInclusionError, [['package.taihe', ['struct BadStructA { \n',
                                              '    a: BadStructB; \n',
                                              '} \n', 
                                              'struct BadStructB { \n',
                                              '    a: BadStructC; \n',
                                              '} \n', 
                                              'struct BadStructC { \n',
                                              '    a: BadStructA; \n',
                                              '} \n', ]]]],
]

if __name__ == "__main__":
    check_exception(test_cases)